feat(Student Data): Check permissions on POSTed data
WISE-Community/WISE-API pull request #147
Opened 2022-06-30 22:01 UTC by hirokiterashima

## Changes
- Test that the student has permissions to save StudentWork/Event/Annotation
- Clean up some code

## Test
- Saving student data works as before if student has the right permissions (e.g. data's run, period, workgroup match that of the student)
- Won't save student data if student does not have the right permissions (e.g. data's run, period, workgroup does not match that of the student)

Closes #146

2022-07-05 19:11 UTC, geoffreykwan requested changes
Saving student work and events properly prevents unauthorized data. Saving an annotation doesn't work properly though.

When a student submits a CRater open response, the score annotation is not saved because the fromWorkgroupId is null. The StudentDataController.canSaveAnnotation() does not handle this case but it should.

Is this the only scenario where the student saves an annotation? I couldn't think of any other scenarios since the teacher is usually the one creating annotations.

This is the annotation the student tries to save after they receive the score from CRater.
```
[{
	"id": null,
	"runId": 3,
	"periodId": 3,
	"fromWorkgroupId": null,
	"toWorkgroupId": 3,
	"nodeId": "node44",
	"componentId": "ldscz6v7wj",
	"studentWorkId": null,
	"localNotebookItemId": null,
	"notebookItemId": null,
	"type": "autoScore",
	"data": {
		"value": 1,
		"autoGrader": "cRater",
		"ideas": []
	},
	"clientSaveTime": 1657046921000,
	"requestToken": "h40qjgb8ma"
}]
```

2022-07-07 00:26 UTC, hirokiterashima commented
Good catch. I check for CRater annotations and allow it now.

2022-07-07 19:23 UTC, geoffreykwan requested changes

2022-07-07 19:23 UTC, geoffreykwan commented on src/main/java/org/wise/vle/web/wise5/StudentDataController.java
> +          return component != null && component.hasField("cRater");
In the component, should we check the enableCRater boolean field instead of the cRater object field? You can disable CRater on a component but the cRater object field will still be there.

2022-07-08 18:58 UTC, geoffreykwan requested changes
I should've noticed this before. In isAutoGradedAnnotation() it only checks if the component has CRater enabled but I think it should also check that the toWorkgroupId is the student's workgroup. Right now you can create auto graded annotations for another workgroup.

2022-07-08 21:12 UTC, geoffreykwan approved these changes
Looks good.

2022-07-08 21:45 UTC, merged

2023-11-27 21:06 UTC, geoffreykwan commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: