fix(Run Info): Allow teachers to request run info by id
WISE-Community/WISE-API pull request #230
Opened 2023-06-28 23:38 UTC by geoffreykwan

## Changes

## Test

Closes #229

2023-06-29 15:40 UTC, hirokiterashima requested changes
Functionality works fine. 

See inline comment.

Also, should the code to handle run info requests be in a new RunInfoController, with the endpoint /api/run/{runId}/info?

2023-06-29 15:40 UTC, hirokiterashima commented on src/main/java/org/wise/portal/service/user/impl/UserServiceImpl.java
> +    return false;
Change to use one return statement.

2023-07-05 18:42 UTC, geoffreykwan commented
Yea maybe we should look into making a RunAPIController or RunInfoController in another issue. There are other run related endpoints in StudentAPIController, TeacherAPIController, and UserAPIController. For example /api/student/run/info which shares code with /api/user/run/info-by-id.

2023-07-10 18:36 UTC, hirokiterashima approved these changes
LGTM

2023-07-11 18:55 UTC, merged

2023-11-27 21:04 UTC, geoffreykwan commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: