Changed CRater API endpoint
WISE-Community/WISE-API pull request #33
Opened 2021-09-03 01:47 UTC by hirokiterashima

## Note
- Since this changes the API, do not update production until also approving accompanying client-side change.
 
## Changes
- Score endpoint now expects json body, with itemId, responseId, and responseText
- Verify endpoint now returns a boolean value
- Refactored CRater endpoint code
- Clarified verify is a GET and score is a POST
- Wrote tests for CRater endpoint

## Test
- Test the verify and score api endpoints using the postman script

Closes #31

2021-09-03 18:43 UTC, geoffreykwan requested changes
Should we use String.format() to create the xml strings?

2021-09-07 23:52 UTC, hirokiterashima commented
We discussed going back to using "+" to concatenate strings for performance reasons.
I also refactored the a bit more (see comments in my last commit).
Please re-review.

2021-09-08 15:15 UTC, geoffreykwan approved these changes
Looks good.

2021-09-08 15:15 UTC, merged

2023-11-27 21:07 UTC, geoffreykwan commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/WISE-Community/WISE-API/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: